# Generated by Django 3.2.9 on 2022-01-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyModel',
            new_name='SpotifyToken',
        ),
    ]
