# Generated by Django 3.2.9 on 2022-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
